### ISSUE TITLE
gradle?

### ISSUE THREAD

**Issue by Swisyn** [one-signal/OneSignal-Android-SDK#1]
Have you tried jar file on android studio? It seems that it doesn't work. Would you please add the library to maven?

**Comment by jkasten2** [comment]
Our SDK jar has been tested to work with Android Studio. You can drop our jar into the libs folder.

Also add the following 2 libraries:
- Android Support Library v4 (v13 works too if you already have it added)
- Google Play services

```

Your build.gradle(Module:) should look like this:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.0'
    compile 'com.google.android.gms:play-services:7.0.0'
}
```

You can then follow the rest of the our [setup guide](http://documentation.onesignal.com/v2.0/docs/installing-the-onesignal-android-sdk#next-you-will-need-to-add-code-to-handle-push-noti) to add the required code and AndroidManifest.xml entries.

**Comment by alvivi** [comment]
You should add this project to Maven Central. Is the only one dependency that is not handled by Maven in our projects.

**Comment by Swisyn** [comment]
Also if you don't know  how to host an library in maven, check it out; http://zserge.com/blog/gradle-maven-publish.html or more users will continue to using pushbots.

**Comment by jkasten2** [comment]
We just made our SDK available on Maven Central and create [installation instructions for Android Studio](https://dash.readme.io/project/gamethrive/v2.0/docs/android-studio-sdk-installation).

Thanks.
