### ISSUE TITLE
Notification received callback option

### ISSUE THREAD

**Issue by varunnayak** [one-signal/OneSignal-Android-SDK#12]
Please provide a callback when a notification is received so that I can show badge on app icon. It would be even better if you could integrate with https://github.com/leolin310148/ShortcutBadger

**Comment by jkasten2** [comment]
We provide a `com.onesignal.BackgroundBroadcast.RECEIVE` action that fire when you set `android_background_data` on our [create notification](https://documentation.onesignal.com/docs/notifications-create-notification) REST API POST call. See our [Android Background Data](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-silent-notifications) information for more details.

Thanks for the link, we will take a look at it.

Thanks.

**Comment by jzeferino** [comment]
Related to this topic. My NotificationOpened callback is called when the user opens the notifications. thats ok. but if the application is in foreground the callback is called and the notification don't appear. There is any way to do that?

**Comment by jkasten2** [comment]
@jzeferino This is expected behavior by default. If you want notification to show even when your app is in the foreground you can call [enableNotificationsWhenActive](https://documentation.onesignal.com/docs/android-sdk-api#enableNotificationsWhenActive) with true after OneSignal init is called.

**Comment by jkasten2** [comment]
@varunnayak Just added Badge support in version [2.2.0](https://github.com/one-signal/OneSignal-Android-SDK/releases/tag/2.2.0). The badge count is automatically set to the number of notifications shown in the Android notification shade.

**Comment by jzeferino** [comment]
@jkasten2 i tested the call ` enableNotificationsWhenActive ` and it worked fine on Android.
In iOs i was expecting the same result but the push notification didn't appear in the notification bar.
It opened a AlertView with the message text and an OK button.
This is normal behaviour?

**Comment by Ralphilius** [comment]
@jkasten2 What happens if we have NotificationOpenHandler and WakefulBroadcastReceiver defined at the same time. What would be the order of execution? How would we return to OneSignal's default behaviour after finished processing the data?

**Comment by ismly** [comment]
can we hide these badges?
