### ISSUE TITLE
I cant't subscribe to One Signal .. why?

### ISSUE THREAD

**Issue by alisherafat** [one-signal/OneSignal-Android-SDK#14]
Hi... my project is completely similar to your github app but i included jar library file (v 2.0.8 ) because i wasn't able to compile your library via compile 'com.onesignal:OneSignal:2.+@aar'. and when i run my app nothing happen and there is no user in my dashboard!  and i get a null pointer exeption (showing in logcat) in my application class on this line > OneSignal.startInit(this)  (just like your sample project) and even during test setting my app in your site i get some error:
Verify that the OneSignal App ID is correct in your app or site.
fa175ba3-7403-495b-a5e9-596736775914
 Run OneSignal.setLogLevel(OneSignal.LOG_LEVEL.DEBUG, OneSignal.LOG_LEVEL.DEBUG); before OneSignal initialization and check your ADB logcat for errors or warnings

But i did these steps :(  can any body what's wrong in my app?
THanks in advance...

**Comment by jkasten2** [comment]
Hello,

Adding `compile 'com.onesignal:OneSignal:2.+@aar'` to your project should automatically download it from Maven Central. Can you verify that you added it to your `build.gradle (Module: app)` file and not your root project one? Also please make sure you are using Android Studio 1.4 or newer. You can also check the "Gradle Console" for any errors. The setup process is much easier if you can use this method.

Also do you have any errors with the following in your project?
```
    compile 'com.google.android.gms:play-services-gcm:+'
    compile 'com.google.android.gms:play-services-analytics:+'
    compile 'com.google.android.gms:play-services-location:+'
```

If you can only get it working with our jar you will need to add the required `AndroidManifest.xml` entries manually. See [2. AndroidManifest.xml](https://documentation.onesignal.com/docs/installing-the-onesignal-android-sdk#2-androidmanifestxml) from our Eclipse setup guide for these entires.

Thanks.

**Comment by alisherafat** [comment]
the problem is i'm using Jcenter() repositories and download libraries from there but your library is in maven!

**Comment by jkasten2** [comment]
Maven Central should be used [by default in Android Studio](http://developer.android.com/tools/building/configuring-gradle.html). However you can add it to your gradle file if it isn't find it.

```
repositories {
   mavenCentral()
}
```

Are you building with gradle directly?

**Comment by codercampos** [comment]
I should recommend using gradle Build tools, from Android Studio is kinda complex (to me at least) to build correctly. With gradle was so simple with just one command to generate de .aar file for Xamarin

**Comment by jkasten2** [comment]
We added a troubleshooting section for this issue.
https://documentation.onesignal.com/docs/android-native-troubleshooting

Feel free to reopen this issue if none of the above resolves it.
