### ISSUE TITLE
One Signal Android SDK getTags can't get all tags from server

### ISSUE THREAD

**Issue by pikachuShy** [one-signal/OneSignal-Android-SDK#17]
When using the getTags function, the return json only return one value for every first time i open the app(uninstall and install). For example in the dashboard, i saw that i already consists three tags, after i called the getTags, it only return me the first tag. 
Is it a bug?

**Comment by jkasten2** [comment]
Currently the getTags method only returns the device's local tags. We will look into changing this logic to fetch the tags the first time from the server.

**Comment by kwiky** [comment]
This is an important feature for us.
How can we delete all server tags without knowing it on the device ?

**Comment by jkasten2** [comment]
@kwiky The work around for now would be to use the OneSignal [View device](https://documentation.onesignal.com/docs/playersid) REST API call to get the current tags. Then you can use the [Edit device](https://documentation.onesignal.com/docs/playersid-1) REST API call to delete the list of tags (See the note on the bottom of the page of how to do this).

I'll shoot for getting a fix for this out in the next minor release in the next few weeks.

**Comment by kwiky** [comment]
thanks @jkasten2, using the REST API is what we have done for now.
We will checkout this next minor release to use the fix instead.

**Comment by jkasten2** [comment]
Fixed this issue in commit 21658df24d041fcdda11256964a5dfc17fdbf96d
