### ISSUE TITLE
Set default color missing

### ISSUE THREAD

**Issue by natangr** [one-signal/OneSignal-Android-SDK#19]
It would be great to be able to set the default color of the notifications on the app side.

**Comment by jkasten2** [comment]
Just added support for this in version 2.3.0 by adding an AndroidManifest.xml meta-data option named. `com.onesignal.NotificationAccentColor.DEFAULT`. It has the same format as our REST API call. Example:
```xml
<!-- Sets all OneSignal notification's accent color to Green by default.  -->
<meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT" android:value="FF00FF00" />
```

**Comment by alexleutgoeb** [comment]
A better approach would be to allow setting an android resource instead of a string, as this is the more intuitive way on Android; e.g.:

```xml
<!-- Sets all OneSignal notification's accent color to Green by default.  -->
<meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT" android:value="@color/tint_color" />
```

**Comment by areavisuale** [comment]
I tried to add the default accent color through manifest (using Unity), but is not applied. Instead I have to insert the color manually when I create the message to see the change. I tried 2 different devices, same problem. I'm missing something?

**Comment by frmeran** [comment]
Same issue

> I tried to add the default accent color through manifest (using Unity), but is not applied. Instead I have to insert the color manually when I create the message to see the change. I tried 2 different devices, same problem. I'm missing something?

**Comment by AppTour0** [comment]
Mesmo problema

> Tentei adicionar a cor de destaque padrão através do manifesto (usando o Unity), mas não é aplicada. Em vez disso, tenho que inserir a cor manualmente quando crio a mensagem para ver a alteração. Eu tentei 2 dispositivos diferentes, mesmo problema. Estou faltando alguma coisa?

**Comment by AppTour0** [comment]
> Same issue
> 
> > I tried to add the default accent color through manifest (using Unity), but is not applied. Instead I have to insert the color manually when I create the message to see the change. I tried 2 different devices, same problem. I'm missing something?


solved the problem by declaring the tag out of activity

**Comment by anthlasserre** [comment]
Still happens...

**Comment by jkasten2** [comment]
@anthlasserre I confirmed this works with OneSignal-Android-SDK 4.0.0 Beta 3.
Make sure you have the `<meta-data>` tag under your `<application>` tag.

```xml
    <application android:name=".application.MainApplication"
        ....
    >
        <!-- Sets all OneSignal notification's accent color to Green by default.  -->
        <meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT" android:value="FF00FF00" />
   </application>
```

For completeness there are a few other ways you can set this color too
* [Via the dashboard or REST API](https://documentation.onesignal.com/docs/customize-notification-icons#small-icon-accent-color)
* Via runtime code in your app via the [NotificationServiceExtension](https://documentation.onesignal.com/docs/40-api-android-native#remotenotificationreceived-method)
   - [Example using `builder.setColor`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.0.0-beta3/Examples/OneSignalDemo/app/src/main/java/com/onesignal/sdktest/notification/NotificationServiceExtension.java#L29)
