### ISSUE TITLE
One signal service restart causing app to also relaunch

### ISSUE THREAD

**Issue by gidimi** [one-signal/OneSignal-Android-SDK#33]
Killing app using android's multitask menu restarts ***/com.onesignal.syncservice which in turn relaunches the app. I've attached a screenshot of the log.

![photo_2016-03-21_17-39-59](https://cloud.githubusercontent.com/assets/16780185/13926317/08f1ddb0-ef8c-11e5-8bd2-4f7ad571136b.jpg)

**Comment by jkasten2** [comment]
Hello,

The `com.onesignal.SyncService` is designed to check and send any tags, settings, or session data to OneSignal in case there was any previous networking issues. The service will stop quickly if there is no work to do.

Do you have code in your `onCreate` in your `Application` class starting an Activity automatically? This could cause your Activity to start when it receive other intents as well.

Thanks.

**Comment by gidimi** [comment]
Thanks, that was it!
