### ISSUE TITLE
Getting Two Push Notification.

### ISSUE THREAD

**Issue by junaidstalkbylove** [one-signal/OneSignal-Android-SDK#35]
I have Implemented my own Push receiver class. But I am getting two push notification. One is my and the other one is default with the messages which I am sending from OneSignal.
I have declared my Receiver in the manifest. 
Please help.
![device-2016-04-11-164321](https://cloud.githubusercontent.com/assets/16255212/14425386/90d82ee0-0004-11e6-94bf-ddb3aa75e327.png)

**Comment by aronmoles** [comment]
Can I turn off notifications that arrive through the sdk and pocesar all notifications through BroadcastReceiver?

Thanks

**Comment by junaidstalkbylove** [comment]
Hey Aronmoles,

You can not turn off notification that arrive through the SDK. If you want to turn off then you need to send push notification from OneSingal without Content.
Then, the content you want to send you need to put that content in the additional field.
Below is the example for the same.

Just put your json in the Value filed with a key.

Then use below mentioned code to parse that JSON in your broadcast receiver.
 Bundle dataBundle = intent.getBundleExtra("data");
            String alert = dataBundle.getString("custom");
            JSONObject obj = new JSONObject(alert);
            if (obj.has("a")) {
                JSONObject o1 = obj.getJSONObject("a");
                JSONObject o = new JSONObject(o1.getString("custom"));
}


I am assuming 'custom' is the key in the additional data field.

Also check background data enabled.

Hope this help.
Thanks.
Junaid

**Comment by jkasten2** [comment]
@aronmoles
junaidstalkbylove will work above. If need to have contents set in your notification we are working on adding a broadcast receiver option.
https://github.com/one-signal/OneSignal-Android-SDK/pull/32#issuecomment-215533646

**Comment by Ghayyas** [comment]
I also faced that issue in my android 6.0

**Comment by jkasten2** [comment]
@Ghayyas There are only two causes that could create duplicated notifications.
1. You have another notification plugin in your app. Run `cordova plugin list` to list them.
2. If you are using our REST API and send more than one with the same contains by mistake.

**Comment by Ghayyas** [comment]
@jkasten2 Thanks. The issue was multiple push plugins in my file. So Just Remove all Plugins and Platform folder and make build again and it works.

**Comment by redoc123** [comment]
@jkasten2 dude.. you save ton of time for me!! cheers.
