### ISSUE TITLE
SDK does not handle push token update on background

### ISSUE THREAD

**Issue by BugsBunnyBR** [one-signal/OneSignal-Android-SDK#36]
As ffar as I could understand of this project, the push token will not be updated if the app is not open for a while.
The token registration process is only triggered in the method onAppFocus, if the user does not open the app for a while, the push token will be invalidated by google and the user will stop receiving push notifications.
Use this link as samples to update the implementation:
https://github.com/googlesamples/google-services/tree/master/android/gcm/app/src/main/java/gcm/play/android/samples/com

**Comment by BugsBunnyBR** [comment]
So, there will be a fix soon? I have seem (literally) some users (work colleagues) not receiving their push notifications even with being sure to have the app installed but not opened over 3 or 4 days...

**Comment by jkasten2** [comment]
I shoot for getting this in our next minor version update however I don't believe this is the issue your seeing.
Google's comment notes that this is called if there security of the token had been compromised.
https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MyInstanceIDListenerService.java#L32

It is more likely an issue with your app being in a "Force Stopped" state due a crash, being closed from Settings>Apps, a 3rd party task killer like greenify, or the device having a modified version of Android which places app's in a stopped state. Xiaomi devices are know to place app's into the "Force Stopped" state.

Lastly make sure you're using our latest 2.3.0 SDK in your app. You can also send the OneSignal player / user ids of the problem devices to support and they can check them on their end.

Thanks.

**Comment by jkasten2** [comment]
@BugsBunnyBR What manufacture is the device you're seeing this issue with? If it is Huawei or Xiaomi you can try the below on the device to see if it has any effect.

* Huawei - Go to Settings > "Protected apps", check your app.
* Xiaomi - Make sure "Auto-start" property enabled for your app in the settings.

I also have a gist of a logcat you can use for reference to confirm if the issue is due to a "force stopped" state.
https://gist.github.com/jkasten2/fb83b1df754cf26df378

**Comment by BugsBunnyBR** [comment]
I am not able to reproduce the problem, I just saw it happening.
One of the devices is a Motorola Moto MAXX.

**Comment by jkasten2** [comment]
@BugsBunnyBR Grab a full logcat from the device if you see the problem again. I should be able to determine the issue from it.
