### ISSUE TITLE
Gray second icon and no badge in API21

### ISSUE THREAD

**Issue by djdance** [one-signal/OneSignal-Android-SDK#38]
On Android 4.x badges appear and notif icon is fine.
But in Android 5.1 two problems:

1. Why there a small gray icon in the right bottom corner? Yes, this is my gray icon for notification, but why here?
2. No badge on screen. (exists on Android 4.x)

![device-2016-04-18-004352](https://cloud.githubusercontent.com/assets/2269720/14590321/0b256046-0500-11e6-8d7e-050b51c83050.png)

**Comment by jkasten2** [comment]
1. This is where the small notification icon is placed when a large icon is set on the notification. This is how the Android OS handles this, see [Google's notification](http://developer.android.com/design/patterns/notifications.html) documentation. 

2. The badge number isn't a standard Android launcher feature. You need to use a launcher on the device that supports them. We use [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) to set the badge number so we only support the launchers it supports.

**Comment by djdance** [comment]
clear, thank you.
