### ISSUE TITLE
failed to resolve: com.onesignal:OneSignal:1.10.2+

### ISSUE THREAD

**Issue by AndreiD** [one-signal/OneSignal-Android-SDK#4]
greetings

when I put in the gradle app file:

compile 'com.onesignal:OneSignal:1.10.2+@aar'

I get.

Error:(38, 13) Failed to resolve: com.onesignal:OneSignal:1.10.2+

Any thoughts on this ?

**Comment by AndreiD** [comment]
works with compile 'com.onesignal:OneSignal:1.+@aar'
but it's not good practice..

**Comment by jkasten2** [comment]
Hello,

1.10.2 was pushed to maven center a few hours before your post. It may have not been available yet or Android Studio did not pull for the latest maven central versions when you built.

We recommend running with the latest with `'com.onesignal:OneSignal:1.+@aar'`, as YY releases (format `XX.YY.ZZ`) normally include bug fixes as well as new features. However, we added a note to our [setup instructions](http://documentation.onesignal.com/v2.0/docs/android-studio-sdk-installation) to use `com.onesignal:OneSignal:1.10.+@aar` if you want to manully control when you go to the next feature version and still important bug fixes.

Thanks.
