### ISSUE TITLE
Getting notificationId on opened

### ISSUE THREAD

**Issue by Ralphilius** [one-signal/OneSignal-Android-SDK#44]
Hello,

Is there anyway we can get a notification id on opened or on received? I would like to have it for logging purpose. Otherwise, if possible, can I access to the database that OneSignal currently used to store notification history?

**Comment by jkasten2** [comment]
@Ralphilius 

You can get the OneSignal notification id from the `i` key nested in `custom` in the [Background Data](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-silent-notifications) receiver.

```Java
JSONObject customJSON = new JSONObject(dataBundle.getString("custom"));
String notificationId = customJSON.getString("i");
```

We do not recommend depending directly on the OneSignal SQL lite database in the SDK as this is designed to be private and the schema could change without notice.

Thanks.

**Comment by Ralphilius** [comment]
Thank you. 

Actually, OneSignal SQL database access was just an alternative in case there's no way to get notification id.

**Comment by Ralphilius** [comment]
@jkasten2 

Is there anyway I can get it in `NotificationOpenedHandler`?

**Comment by jkasten2** [comment]
@Ralphilius There isn't at this time, I'll look into adding it.

In the meantime you can add your own `data` key/value which might work as a workaround depending on what you need.

**Comment by jkasten2** [comment]
Merging with #40 as these are both requesting the notification id on the opened notification callback.
