### ISSUE TITLE
Exception: java.lang.RuntimeException at com.onesignal.AndroidSupportV4Compat$ContextCompat.checkSelfPermission(AndroidSupportV4Compat.java:46)

### ISSUE THREAD

**Issue by DimaKoz** [one-signal/OneSignal-Android-SDK#48]
I got the [crashlog] (https://github.com/one-signal/OneSignal-Android-SDK/files/253639/log.txt).
About devices:
<img width="960" alt="screen shot 2016-05-08 at 0 56 38" src="https://cloud.githubusercontent.com/assets/3092276/15094763/1c9cba66-14c0-11e6-803c-54f383757b8b.png">

**Comment by jkasten2** [comment]
Thanks for the log, added a catch around this for this rare exception to prevent a crash.
b2f0fc0a393663b80a6e920307f4055d2520f2df
