### ISSUE TITLE
Error:(46, 21) java: package com.onesignal does not exist

### ISSUE THREAD

**Issue by raysango** [one-signal/OneSignal-Android-SDK#50]
Hi I'm trying to use this plugin to push notification to Android device,I created the Cordova app (v 6.1.1) and installed all the required SDK extras but when I try to compile the project I get the error
Error:(46, 21) java: package com.onesignal does not exist , all I find out that I might be missing some SDKs but I'm not sure which one, I've installed Google Play Services 29.00 , Google Repository 25.0.0 , Android Support Repository 31.0.0, Intel x86 Emulator 6.0.1

I'm using android:targetSdkVersion="23" and Android Studio

**Comment by jkasten2** [comment]
@raysango Could let us know exactly where the follow error is being outputted from?
`Error:(46, 21) java: package com.onesignal does not exist`

Are you building with `cordova build android` or opening the project with Eclipse or Android Studio and building from there?

**Comment by raysango** [comment]
Yes I used cordova build android and then imported to Android studio, the error is outputted from Android Studio when I try to run the app

**Comment by jkasten2** [comment]
I have seen this issue before with Cordova, it seems to be a bug with it not setting up the gradle project correctly. It only happens when building from outside of Cordova.

You need to add OneSignal and the Google Play services to your gradle file noted in our Android Studio guide.
```
dependencies {
    compile 'com.onesignal:OneSignal:2.+@aar'
    compile 'com.google.android.gms:play-services-gcm:+'
    compile 'com.google.android.gms:play-services-analytics:+'
    compile "com.google.android.gms:play-services-location:+"
}
```
https://documentation.onesignal.com/docs/android-studio-sdk-installation
