### ISSUE TITLE
Addition of Notification Id in Notification for cancellation of OneSignal Notification

### ISSUE THREAD

**Issue by amgu** [one-signal/OneSignal-Android-SDK#52]
There may be a case when user receives  a notification for some information. And user does not click on the notification instead user opens the application from menu normally and view the information received via notification, in this case there is no use of that notification . I want to clear that single notification from notification drawer.

 I want to use below code

NotificationManager notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
notificationManager.cancel(NOTIFICATION_ID);

For this i need NOTIFICATION_ID to be set by your SDK while creating notification.
So please do this enhancement..
Thanks

**Comment by jkasten2** [comment]
This is now possible with our 2.4.0 SDK by using a `NotificationExtenderService`.
See [Background Data and Notification Overriding](https://documentation.onesignal.com/v2.0/docs/android-notification-customizations#background-data-and-notification-overriding) to do this. After you follow step 1 &  2, step 3 will show you how to get the `NOTIFICATION_ID` your looking for.

Feel free to re-open this issue if you run into any problems.

**Comment by DenisBronx** [comment]
Hi, i'm using 2.4.1 SDK and i'm not able to cancel the notification by the id that returns from OSNotificationDisplayedResult. 

From the debug i can see that 2 notificationId are generated (one for the summary notification and the other for individual notification). In the OSNotificationDisplayedResult object that returns i have only the notificationId used for individual notifications and if i try to cancel the notification from that id it doesn't work, but if i try to cancel it using the notificationId of the summary notification that i previously seen in the debug it works.
