### ISSUE TITLE
Issue with com.loopj.android:android-async-http:1.4.9 lib integration

### ISSUE THREAD

**Issue by jagatappv** [one-signal/OneSignal-Android-SDK#6]

**Comment by jkasten2** [comment]
We are removing the loopj library from our SDK in the next major release. I'll update this issue when it is released.

Thanks.

**Comment by jagatappv** [comment]
Can you tell me the date when you will release a new version with updates after removing the loopj lib?

Thanks for support

**Comment by sealskej** [comment]
+1

**Comment by jkasten2** [comment]
Version 2.0.0 of the SDK is released which includes the removal of android-async-http (loopj) that fixes this conflict issue. See the release and update notes for details
https://github.com/one-signal/OneSignal-Android-SDK/releases/tag/2.0.0

Thanks.
