### ISSUE TITLE
OneSignal.init cause Activity leaking

### ISSUE THREAD

**Issue by ITurchenko** [one-signal/OneSignal-Android-SDK#7]
LeakCanary reports that activity used in OneSignal.Init method is keeping in memory after going to another activities.

**Comment by jkasten2** [comment]
We are changing our Activity handling in the next major release of our SDK. I'll update this issue when it is available.

Thanks.

**Comment by sealskej** [comment]
+1

**Comment by jkasten2** [comment]
Version 2.0.0 of the SDK is released fixes the Activity leak issue. See the release and update notes for details.
https://github.com/one-signal/OneSignal-Android-SDK/releases/tag/2.0.0

Feel free to reopen this issue if you're still seeing an Activity leak.

Thanks.
