### ISSUE TITLE
DatabaseNotClosedException raised when notification arrives

### ISSUE THREAD

**Issue by abhimediratta** [one-signal/OneSignal-Android-SDK#8]
I'm running the app in StrictMode. I get the following exception when notification comes on the app:

Finalizing a Cursor that has not been deactivated or closed. database = /data/data/com.patientapp/databases/OneSignal.db, table = notification, query = SELECT notification_id FROM notification WHERE notification_id = ?
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode: android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:98)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1200)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at com.onesignal.OneSignal.isDuplicateNotification(OneSignal.java:1263)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at com.onesignal.OneSignal.isValidAndNotDuplicated(OneSignal.java:1290)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:48)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:66)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.os.Looper.loop(Looper.java:136)
12-02 17:20:45.025 4035-4044/com.patientapp E/StrictMode:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jkasten2** [comment]
Thanks for reporting the issue, we will be looking into this issue next week. Could you provide step by step instructions to reproduce this issue to help us quickly fix it?

Thanks.

**Comment by jkasten2** [comment]
Just fixed the open cursor from your stack trace as well as a few other open resources in commit 4028737ff3d839dbcdac14352c7b3902119381bd

Thanks.
