### ISSUE TITLE
Gradle configuration

### ISSUE THREAD

**Issue by dbystVF** [one-signal/OneSignal-Android-SDK#9]
Hey..I have my android project. I created 2 applications in OneSignal...Staging and Production...
How can I setup 2 different onesignal_app_id: for different build types in my project.

android {
    defaultConfig {
        manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                                onesignal_app_id: "b2f7f966-d8cc-11e4-bed1-df8f05be55ba",
                                onesignal_google_project_number: "703322744261"]
    }
 }

**Comment by jkasten2** [comment]
Hello,

You can define different `manifestPlaceholders` for each of your `buildTypes`.

Example:
```gradle
buildTypes {
   debug {
      defaultConfig {
         manifestPlaceholders = [manifestApplicationId          : "${applicationId}",
                                 onesignal_app_id               : "11111111-1111-1111-1111-111111111111",
                                 onesignal_google_project_number: "111111111"]
       }
   }

   release {
      defaultConfig {
         manifestPlaceholders = [manifestApplicationId          : "${applicationId}",
                                 onesignal_app_id               : "22222222-2222-2222-2222-222222222222",
                                 onesignal_google_project_number: "222222222"]
      }
   }
}
```

Thanks.

**Comment by dbystVF** [comment]
Yep, exactly what i need...Thanks

**Comment by danielgomezrico** [comment]
+1 to move those setups to code, I mean something like `OneSignal.init(manifestAppId, appId, projectNumber)`.

**Comment by txusms** [comment]
+1 @danielgomezrico 
My workaround. In AndroidManifest.xml file:
`<meta-data android:name="onesignal_app_id"
            android:value="@string/my_onesignal_app_id"
            tools:replace="android:value"/>`
        `<meta-data android:name="onesignal_google_project_number"
            android:value="@string/my_onesignal_google_project_number"
            tools:replace="android:value"/>`
It works fine with Android Studio 2.2.

**Comment by francoisrouault** [comment]
What if different product flavors (+ Staging and Production build types) ?!

I used `OneSignal.init(appId, projectNumber,...)` but I am still forced to add OneSignal's `manifestPlaceholders` (with dummy values then) in my `android.defaultConfig` otherwise I get `Manifest merger` errors which is not clean code...

**Comment by dev-JE02** [comment]
@jkasten2 this still doesn't work even though I put it in different build types' defaulConfig. I am using Android Studio 3.0 Canary build

**Comment by jkasten2** [comment]
@dbystVF Let's continue discussion on #143

**Comment by jdestremps** [comment]
We need to be able to set the appId, etc. programmatically, so we can switch environments on the fly for different pre-prod versions and re-initialize the OneSignal stuff whenever we want.  Limiting it to the manifest is not very flexible.
